#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    # Create the user radxa 
    systemd-sysusers || true
    # Create tempfiles
    systemd-tmpfiles --create || true
    rsetup set_autologin_status oem lightdm.service ON
    rsetup set_autologin_status oem gdm.service ON
    rsetup set_autologin_status oem sddm.service ON
    rsetup set_autologin_status oem getty@.service ON
    rsetup set_autologin_status oem serial-getty@.service ON
fi

#DEBHELPER#

exit 0
