#!/bin/sh
set -e

#DEBHELPER#

case $1 in
    remove)
        rsetup set_autologin_status oem lightdm.service OFF
        rsetup set_autologin_status oem gdm.service OFF || true
        rsetup set_autologin_status oem sddm.service OFF
        rsetup set_autologin_status oem getty@.service OFF
        rsetup set_autologin_status oem serial-getty@.service OFF
        # Lock the user
        usermod -L -e 1 oem || true
        rm -f /etc/ssh/sshd_config.d/99-oem.conf /etc/sudoers.d/99-oem
        ;;
esac

exit 0
