#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    # Create the user radxa 
    systemd-sysusers || true
    # Create tempfiles
    systemd-tmpfiles --create || true
    rsetup set_autologin_status lightdm.service oem on
    rsetup set_autologin_status gdm.service oem on
    rsetup set_autologin_status sddm.service oem on
    rsetup set_autologin_status getty@.service oem on
    rsetup set_autologin_status serial-getty@.service oem on
fi

#DEBHELPER#

exit 0
